language: sh

env: SHUNIT2_VERSION=2.1.7

install:
  - curl -sSL https://github.com/kward/shunit2/archive/v$SHUNIT2_VERSION.tar.gz -o shunit2.tar.gz
  - tar -zxf shunit2.tar.gz
  - cp shunit2-$SHUNIT2_VERSION/shunit2 ./shunit2

script: ./test.sh

notifications:
  email: false
